# NumPy

In [1]:
my_list = [23,45,234,5]

In [2]:
my_other_list = [34,23,56,3]

In [3]:
my_list+my_other_list

[23, 45, 234, 5, 34, 23, 56, 3]

In [2]:
import numpy as np

In [5]:
my_first_array = np.array(my_list)
my_first_array


array([ 23,  45, 234,   5])

In [6]:
my_2_array = np.array(my_other_list)
my_2_array

array([34, 23, 56,  3])

In [7]:
combined_array = my_first_array + my_2_array
combined_array

array([ 57,  68, 290,   8])

In [8]:
my_first_array

array([ 23,  45, 234,   5])

# Pandas

In [3]:
import pandas as pd

In [10]:
df = pd.DataFrame({"col1":[0,1,3], "col2":[0,0,100]})
df

col1  col2
0     0     0
1     1     0
2     3   100

In [11]:
ar = pd.Series([1,2,3,4,5,6])
print(ar)
ar.index = ['A','B','C','D','E','F']
print(ar)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
A    1
B    2
C    3
D    4
E    5
F    6
dtype: int64


In [12]:
data = [450,650,870]
Sales = pd.Series(data,index=['Don','Mike','Edwin'],name="Sales")
print(Sales.index)
Sales

Index(['Don', 'Mike', 'Edwin'], dtype='object')


Don      450
Mike     650
Edwin    870
Name: Sales, dtype: int64

In [13]:
print(Sales.index)
print(Sales.values)
print(Sales.dtype)

Index(['Don', 'Mike', 'Edwin'], dtype='object')
[450 650 870]
int64


In [14]:
df.to_numpy()

array([[  0,   0],
       [  1,   0],
       [  3, 100]], dtype=int64)

In [15]:
Sales['Mike']

650

In [16]:
Sales[1]

650

In [17]:
Sales[0:2]

Don     450
Mike    650
Name: Sales, dtype: int64

In [18]:
Sales>500

Don      False
Mike      True
Edwin     True
Name: Sales, dtype: bool

In [19]:
Sales[[False,True,True]]

Mike     650
Edwin    870
Name: Sales, dtype: int64

In [20]:
print(Sales)
sales_dict = Sales.to_dict()
sales_dict

Don      450
Mike     650
Edwin    870
Name: Sales, dtype: int64


{'Don': 450, 'Mike': 650, 'Edwin': 870}

In [21]:
sales_ser = pd.Series(sales_dict)
sales_ser

Don      450
Mike     650
Edwin    870
dtype: int64

In [22]:
new_sales = pd.Series(Sales, index=['Don', 'Mike', 'Sally', 'Edwin', 'Lucy'])
new_sales

Don      450.0
Mike     650.0
Sally      NaN
Edwin    870.0
Lucy       NaN
Name: Sales, dtype: float64

In [23]:
new_sales[pd.notna(new_sales)]

Don      450.0
Mike     650.0
Edwin    870.0
Name: Sales, dtype: float64

# Pandas DataFrames

DataFrames are two-dimensional, size-mutable, potentially heterogeneous tabular data structure contains labeled axes.

## Creating DataFrames

### Creating a DataFrame from a dictionary

In [24]:
new_dict = {
    'Name':['Tom','Jane','Steve','Lucy'],
    'Sales':[250,500,350,400],
    'Date':[2022,2020,2021,2022]
}
df = pd.DataFrame(new_dict)
df

Name  Sales  Date
0    Tom    250  2022
1   Jane    500  2020
2  Steve    350  2021
3   Lucy    400  2022

In [25]:
df.values

array([['Tom', 250, 2022],
       ['Jane', 500, 2020],
       ['Steve', 350, 2021],
       ['Lucy', 400, 2022]], dtype=object)

In [26]:
df.index

RangeIndex(start=0, stop=4, step=1)

### Adding custom index

In [27]:
df_index = pd.DataFrame(new_dict, index=['rank1','rank2','rank3','rank4'])
df_index

Name  Sales  Date
rank1    Tom    250  2022
rank2   Jane    500  2020
rank3  Steve    350  2021
rank4   Lucy    400  2022

In [28]:
df_index.index.name="Rank"

In [29]:
df_index

Name  Sales  Date
Rank                     
rank1    Tom    250  2022
rank2   Jane    500  2020
rank3  Steve    350  2021
rank4   Lucy    400  2022

In [30]:
df_index.columns

Index(['Name', 'Sales', 'Date'], dtype='object')

In [31]:
new_dict_v2 = {
    'Name':['Tom','Jane','Steve','Lucy'],
    'Sales':[250,500,350,400],
    'Date': [2022,2020,2021,2022],
    'Rank': ['rank1','rank2','rank3','rank4']
}

df2=pd.DataFrame(new_dict_v2)
df2

Name  Sales  Date   Rank
0    Tom    250  2022  rank1
1   Jane    500  2020  rank2
2  Steve    350  2021  rank3
3   Lucy    400  2022  rank4

In [32]:
df2.set_index("Rank",inplace=True)
# Inplace = True, means that the change to dataframe is made permanent

In [33]:
df2

Name  Sales  Date
Rank                     
rank1    Tom    250  2022
rank2   Jane    500  2020
rank3  Steve    350  2021
rank4   Lucy    400  2022

In [34]:
# Multi Level Indexes (hierarchical indexes)

df2.set_index(['Rank','Name'],inplace=True)
df2

KeyError: "None of ['Rank'] are in the columns"

In [ ]:
df2.sort_index(level=["Name","Rank"],ascending=[False,True])

In [ ]:
df2.reset_index()

## Subsetting DataFrame

Two ways:

* Square Brackets

* Advanced Mehtods
  * loc
  * iloc

In [ ]:
df

In [ ]:
print(type(df["Name"]))
print(df["Name"])
print(type(df[["Name"]]))
print(df[["Name"]])

In [ ]:
df[df.Name=='Tom']

In [ ]:
# Filtering DataFrames
df[(df["Sales"]>300) & (df["Date"]>2020)]

In [ ]:
df[df["Date"].isin([2020,2022])]

## loc and iloc

loc[row_label, column_label]
iloc[row_position, column_position]

## loc - Label based access

In [42]:
new_dict_v2 = {
    'Name':['Tom','Jane','Steve','Lucy'],
    'Sales':[250,500,350,400],
    'Date': [2022,2020,2021,2022],
    'Rank': ['rank1','rank2','rank3','rank4']
}

df2=pd.DataFrame(new_dict_v2)
df2_rank=df2.set_index("Rank")
df2_rank

Name  Sales  Date
Rank                     
rank1    Tom    250  2022
rank2   Jane    500  2020
rank3  Steve    350  2021
rank4   Lucy    400  2022

In [36]:
df2_rank.loc["rank1":"rank1",["Name","Sales"]]
# Endpoint is included in loc and iloc

Name  Sales
Rank             
rank1  Tom    250

In [37]:
df2_rank.iloc[0:2,[1]]

Sales
Rank        
rank1    250
rank2    500

In [40]:
df.loc[df.Sales>300,['Name','Sales']]

Name  Sales
1   Jane    500
2  Steve    350
3   Lucy    400

In [43]:
df2_rank.loc[['rank1','rank3']]

Name  Sales  Date
Rank                     
rank1    Tom    250  2022
rank3  Steve    350  2021

### iloc - position based access

If you want to subset Pandas DataFrames based on their position, or index

In [44]:
df2_rank.iloc[:2,2:]

Date
Rank       
rank1  2022
rank2  2020

# Assignment:
# Pre-defined lists

In [4]:
country = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
drives_right =  [True, False, False, False, True, True, True]
cars_per_cap = [809, 731, 588, 18, 200, 70, 45]
row_labels = ['US', 'AUS', 'JPN', 'IN', 'RU', 'MOR', 'EG']

In [5]:
#step1: Create dictionary my_dict with three key:value pairs: my_dict
my_dict = {"Country":country,"Drives_Right":drives_right,"cars_per_cap":cars_per_cap}
my_dict

{'Country': ['United States',
  'Australia',
  'Japan',
  'India',
  'Russia',
  'Morocco',
  'Egypt'],
 'Drives_Right': [True, False, False, False, True, True, True],
 'cars_per_cap': [809, 731, 588, 18, 200, 70, 45]}

In [6]:
df_a = pd.DataFrame(my_dict)
df_a

Country  Drives_Right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

In [7]:
df_a.index = row_labels

In [8]:
df_a

Country  Drives_Right  cars_per_cap
US   United States          True           809
AUS      Australia         False           731
JPN          Japan         False           588
IN           India         False            18
RU          Russia          True           200
MOR        Morocco          True            70
EG           Egypt          True            45

In [9]:
print(type(df_a['Country']))
df_a['Country']

<class 'pandas.core.series.Series'>


US     United States
AUS        Australia
JPN            Japan
IN             India
RU            Russia
MOR          Morocco
EG             Egypt
Name: Country, dtype: object

In [10]:
print(type(df_a[['Country']]))
df_a[['Country']]

<class 'pandas.core.frame.DataFrame'>


Country
US   United States
AUS      Australia
JPN          Japan
IN           India
RU          Russia
MOR        Morocco
EG           Egypt

In [11]:
df_a[['Country','Drives_Right']]

Country  Drives_Right
US   United States          True
AUS      Australia         False
JPN          Japan         False
IN           India         False
RU          Russia          True
MOR        Morocco          True
EG           Egypt          True

In [12]:
df_a[:3]

Country  Drives_Right  cars_per_cap
US   United States          True           809
AUS      Australia         False           731
JPN          Japan         False           588

In [16]:
# df_a.iloc[3:6]
df_a.iloc[[3,4,5],:]

Country  Drives_Right  cars_per_cap
IN     India         False            18
RU    Russia          True           200
MOR  Morocco          True            70

In [60]:
df_a[df_a.Country == "Japan"]

Country  Drives_Right  cars_per_cap
JPN   Japan         False           588

In [62]:
df_a[df_a.Country.isin(["Australia","Egypt"])]

Country  Drives_Right  cars_per_cap
AUS  Australia         False           731
EG       Egypt          True            45

In [63]:
df_a.loc[df_a.Country=="Morocco",['Drives_Right']]

Drives_Right
MOR          True

# Pandas Series Exercises

Completing Exercises from w3resource

In [ ]:
# 1)

pd.Series([1,2,3,4,5])

In [ ]:
# 2)
series = pd.Series([1,2,3,4,5])
l_series = series.to_list()
print(l_series)
print(type(l_series))

In [ ]:
# 3)
s1 = pd.Series([1,2,3,4,0])
s2 = pd.Series([2,3,4,5,2])
print(s1+s2)
print(s2-s1)
print(s1*s2)
print(s2/s1)

In [ ]:
# 4)
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([2,3,4,5,6])
s1>s2

In [ ]:
# 5)
diction = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
series = pd.Series(diction)
series

In [ ]:
# 6)
np_array = np.array([10,20,30,40,50])
series = pd.Series(np_array)
series

In [ ]:
# 7)
series = pd.Series([100,200,'python',300.12,400])
print(series)
print(pd.to_numeric(series, errors='coerce'))

In [ ]:
# 8)
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(d)
print(df)
series = pd.Series(df['col1'])
series

In [ ]:
# 9)
series = pd.Series([100,200,'python',300.12,400])
print(series)
ar = np.array(series)
print(ar)
print(ar.dtype)

In [ ]:
# 10
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']])
s = s.apply(pd.Series).stack().reset_index(drop=True)
s

In [ ]:
# 11
series = pd.Series(['100','200','python','300.12','400'])
series = series.sort_values(ascending=True)
series

In [ ]:
# 12
series = pd.Series(['100','200','python','300.12','400'])
series = series.append(pd.Series(['500', 'php']))
series

In [ ]:
# 13
series = pd.Series([0,1,2,3,4,5,6,7,8,9,10])
sub_series = series[0:6]
sub_series

In [ ]:
# 14
series = pd.Series([1,2,3,4,5],index=['A','B','C','D','E'])
print(series)
series = series.reindex(index = ['B','A','C','D','E'])
series

In [ ]:
# 15
series = pd.Series([1,2,3,4,5,6,7,8,9,5,3])
print(series.mean())
print(series.std())

In [ ]:
# 16
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([2,4,6,8,10])

s1[~s1.isin(s2)]

In [ ]:
# 17
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([2,4,6,8,10])

pd.concat([s1[~s1.isin(s2)], s2[~s2.isin(s1)]]).reset_index(drop=True)

In [ ]:
# 18
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))
print(num_series.min())
print(num_series.quantile(0.25))
print(num_series.median())
print(num_series.quantile(0.75))
print(num_series.max())

In [ ]:
# 19
num_series = pd.Series(np.take(list('0123456789'), np.random.randint(10, size=40)))
num_series.value_counts()

In [ ]:
# 20
np.random.RandomState(100)
num_series = pd.Series(np.random.randint(1, 5, [15]))
# Not finished

# Pandas DataFrames Exercises

Exercises on DataFrames from w3resource on pandas dataframes

In [18]:
# 1
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]})
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [19]:
# 2
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data,index=labels)
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [20]:
# 3
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


In [21]:
# 4
df[:3]

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

In [25]:
# 5
df.filter(['name', 'score'])
#  or
df[['name','score']]

name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

In [29]:
# 6
df.iloc[[1,3,5,6]][['name','score']]
# Better than there solution

name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

In [30]:
# 7
df[df.attempts > 2]

name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

In [32]:
# 8
print(f'Number of Rows: {len(df.index)}')
print(f'Number of Columns: {len(df.columns)}')

Number of Rows: 10
Number of Columns: 4


In [45]:
# 9
df[df['score'].isna()]

name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

In [48]:
# 10
df.loc[(df.score>=15)&(df.score<=20)]

name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

In [50]:
# 11
df.loc[(df.attempts<2)&(df.score>=15)]

name  score  attempts qualify
j  Jonas   19.0         1     yes

In [54]:
# 12
df.loc['d','score'] = 11.5
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [60]:
# 13
sum(df.attempts)

19

In [61]:
# 14
df.score.mean()

13.333333333333334

In [66]:
# 15
df.loc['k'] = ["Suresh",15.5,1,"yes"]
print(df)
df.drop(['k'], inplace=True)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [69]:
# 16
df.sort_values(['name','score'],ascending=[False,True])

name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

In [72]:
# 17
df['qualify'].replace(['yes','no'],[True,False])

a     True
b    False
c     True
d    False
e    False
f     True
g     True
h    False
i    False
j     True
Name: qualify, dtype: bool

In [73]:
# 18
df['name'].replace('James','Suresh')

a    Anastasia
b         Dima
c    Katherine
d       Suresh
e        Emily
f      Michael
g      Matthew
h        Laura
i        Kevin
j        Jonas
Name: name, dtype: object

In [74]:
# 19
df.drop(['attempts'], axis=1)

name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James   11.5      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes

In [75]:
# 20
df['color'] = ['Red','Blue','Orange','Red','White','White','Blue','Green','Green','Red']
df

name  score  attempts qualify   color
a  Anastasia   12.5         1     yes     Red
b       Dima    9.0         3      no    Blue
c  Katherine   16.5         2     yes  Orange
d      James   11.5         3      no     Red
e      Emily    9.0         2      no   White
f    Michael   20.0         3     yes   White
g    Matthew   14.5         1     yes    Blue
h      Laura    NaN         1      no   Green
i      Kevin    8.0         2      no   Green
j      Jonas   19.0         1     yes     Red

In [76]:
# 21
exam_data = {'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}
df = pd.DataFrame(exam_data)
for index, row in df.iterrows():
    print(f'{row["name"]} {row["score"]}')

Anastasia 12.5
Dima 9.0
Katherine 16.5


In [79]:
# 22
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data,index=labels)

df.columns.to_list()

['name', 'score', 'attempts', 'qualify']

In [80]:
# 23
d = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}
df = pd.DataFrame(data=d)
df.rename(columns={'col1':'Column1','col2':'Column2','col3':'Column3'})

Column1  Column2  Column3
0        1        4        7
1        2        5        8
2        3        6        9

In [84]:
# 24
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}
df = pd.DataFrame(data=d)
df[df.col1 == 4]

col1  col2  col3
1     4     5     8
3     4     7     0

In [85]:
# 25
df[['col3','col2','col1']]

col3  col2  col1
0     7     4     1
1     8     5     4
2     9     6     3
3     0     7     4
4     1     8     5

In [88]:
# 26
df.append({'col1':10,'col2':11,'col3':12},ignore_index=True)

C:\Users\Coach\AppData\Local\Temp\ipykernel_18036\1639652524.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append({'col1':10,'col2':11,'col3':12},ignore_index=True)


col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12

In [ ]:
# 27
df.to_csv('new_file.csv',sep='\t',index=False)

In [91]:
# 28
df1 = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
                    'city': ['California', 'Los Angeles', 'California', 'California', 'California', 'Los Angeles', 'Los Angeles', 'Georgia', 'Georgia', 'Los Angeles']})
df1.groupby('city').nunique()


name
city             
California      4
Georgia         2
Los Angeles     4

In [95]:
# 29
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}
df = pd.DataFrame(data=d)
df[df.col3 != 8]

col1  col2  col3
0     1     4     7
2     3     6     9
3     4     7     0
4     5     8     1

In [96]:
# 30
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
print("Original DataFrame")
print(df)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
